### ISSUE TITLE
Github pages to show results

### ISSUE THREAD

**Issue by klapaukh** [UCL/i_newspaper_rods#11]
See if you can set up a github pages page to view the results of the analysis scripts

**Comment by klapaukh** [comment]
It looks like this possible. The big questions are: 
 
- what should actually be there? 
   - An index to all our analyses?
   - Only analyses which are published
- Is it ok to publically share data that has not yet been turned into a publication?

**Comment by raquelalegre** [comment]
If anything a list to all our analysis would be best, however I do worry about sharing unpublished results. @TessaC what do you think?

**Comment by TessaC** [comment]
Hello both, I am also a bit wary at this stage to share unpublished results, as this might become tricky especially since we are dealing with these datasets which come with all these copyright issues.

**Comment by raquelalegre** [comment]
OK, so let's not do the github pages work. The license should be OK, I think, as long as we don't share extracts of the text of more than... I think it was 100 characters or something similar. 

Closing.
